name: stashbox
services:
  # API DATABASE
  postgresql-api-db:
    image: postgres:18.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${API_DB_NAME:-stashboxdb}"
      POSTGRES_USER: "${API_DB_USER:-stashboxdbuser}"
      POSTGRES_PASSWORD: "${API_DB_PASSWORD:-stashboxdbpassword}"
    networks:
      - stashbox-network
    ports:
      - "${API_DB_PORT}:5432"
    volumes:
      - ./data/postgresql_api_db:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

  # API
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      postgresql-api-db:
        condition: service_healthy
    environment:
      DB_URL: "jdbc:postgresql://postgresql-api-db:5432/${API_DB_NAME}"
      DB_USER: "${API_DB_USER}"
      DB_PASSWORD: "${API_DB_PASSWORD}"
      SERVER_PORT: "${API_SERVER_PORT:-9001}"
    networks:
      - stashbox-network
    env_file:
      - .env
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"

networks:
  stashbox-network:
    driver: bridge