spring.application.name=backend
server.port=9001

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/stashbox
spring.datasource.username=stashbox
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

# Datasource Dev-only logging
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log levels
logging.level.root=INFO
logging.level.org.springframework.boot=INFO
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR