spring.application.name=backend
server.port=9001

spring.messages.basename=messages

# For enabling exception handler 404
spring.web.resources.add-mappings=false

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/stashboxdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

# --- Security (JWT / OAuth2) ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/stashbox

# No SQL logging
spring.jpa.properties.hibernate.show_sql=false

# Minimal logging
logging.level.root=WARN
logging.level.org.springframework.boot=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN